# Generated by Django 3.0.2 on 2020-03-21 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, null=True, unique=True, verbose_name='código')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='descripción del bien')),
                ('model_name', models.CharField(blank=True, max_length=65, null=True)),
                ('serial', models.CharField(blank=True, max_length=25, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('dispose_date', models.DateField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=165, null=True)),
                ('user_function', models.CharField(blank=True, max_length=165, null=True)),
                ('leasing', models.CharField(blank=True, max_length=25, null=True)),
                ('info', models.CharField(blank=True, max_length=10000, null=True, verbose_name='información adicional')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Area', verbose_name='area')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Brand', verbose_name='marca')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Group')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Status', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'activo',
                'verbose_name_plural': 'activo fijo',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='fecha de inventario')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Area', verbose_name='area de levantamiento')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'levantar de inventario',
            },
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Orden de compra'), (2, 'Orden de entrada'), (3, 'Orden de salida'), (4, 'Mantenimiento'), (5, 'Baja')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=6, null=True, verbose_name='número')),
                ('date_time', models.DateTimeField(verbose_name='fecha y hora')),
                ('origin_person', models.CharField(blank=True, max_length=125, null=True, verbose_name='persona que envia')),
                ('origin_charge', models.CharField(blank=True, max_length=125, null=True, verbose_name='cargo de la persona que envia')),
                ('destiny_person', models.CharField(blank=True, max_length=125, null=True, verbose_name='persona que recibe')),
                ('destiny_charge', models.CharField(blank=True, max_length=125, null=True, verbose_name='cargo de la persona que recibe')),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('destiny_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destiny_area', to='utils.Area', verbose_name='area que recibe')),
                ('origin_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_area', to='utils.Area', verbose_name='area que envia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traslado',
            },
        ),
        migrations.CreateModel(
            name='TranslateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=250, null=True, verbose_name='comentarios')),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translates', to='backend.Active', verbose_name='activo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Status', verbose_name='estado')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.Translate')),
            ],
            options={
                'verbose_name': 'item',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=250, null=True, verbose_name='comentarios')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Active')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Inventory')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
            ],
            options={
                'verbose_name': 'entrada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.CreateModel(
            name='Maintanance',
            fields=[
            ],
            options={
                'verbose_name': 'matenimiento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.CreateModel(
            name='Outcoming',
            fields=[
            ],
            options={
                'verbose_name': 'salida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.CreateModel(
            name='UnActive',
            fields=[
            ],
            options={
                'verbose_name': 'orden de baja',
                'verbose_name_plural': 'dar de baja',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
    ]
