# Generated by Django 3.0.2 on 2020-01-30 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='marca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nombre en la base de datos')),
                ('label', models.CharField(max_length=65, verbose_name='etiqueta para el usuario')),
                ('input_type', models.CharField(choices=[('TEXT', 'TEXT')], max_length=4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, null=True, verbose_name='código')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='descripción del bien')),
                ('model_name', models.CharField(blank=True, max_length=65, null=True)),
                ('serial', models.CharField(blank=True, max_length=25, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Brand', verbose_name='marca')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Group')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status', verbose_name='estado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
