# Generated by Django 3.0.2 on 2020-01-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_area_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Area', verbose_name='area'),
        ),
    ]
