# Generated by Django 3.0.2 on 2020-02-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_active_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='info',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='información adicional'),
        ),
    ]
