# Generated by Django 3.0.2 on 2020-02-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_active_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': 'activo'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'área'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'marca'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'pais'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'grupo'},
        ),
        migrations.AlterModelOptions(
            name='groupfield',
            options={'verbose_name': 'campo'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'estado'},
        ),
        migrations.AlterField(
            model_name='groupfield',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='backend.Group'),
        ),
    ]
