# Generated by Django 3.0.2 on 2020-02-14 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_auto_20200214_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=6, null=True, verbose_name='número')),
                ('date_time', models.DateTimeField(verbose_name='fecha y hora')),
                ('origin_person', models.CharField(max_length=125, verbose_name='persona que envia')),
                ('origin_charge', models.CharField(max_length=125, verbose_name='cargo de la persona que envia')),
                ('destiny_person', models.CharField(max_length=125, verbose_name='persona que recibe')),
                ('destiny_charge', models.CharField(max_length=125, verbose_name='cargo de la persona que recibe')),
                ('comments', models.TextField(blank=True, max_length=500, null=True)),
                ('destiny_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_area', to='backend.Area', verbose_name='area que recibe')),
                ('origin_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_area', to='backend.Area', verbose_name='area que envia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'pais', 'verbose_name_plural': 'paises'},
        ),
        migrations.CreateModel(
            name='TranslateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translates', to='backend.Active', verbose_name='activo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status', verbose_name='estado')),
                ('translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.Translate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
