# Generated by Django 3.0.2 on 2020-02-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200214_0504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translate',
            options={'verbose_name': 'traslado'},
        ),
        migrations.AlterModelOptions(
            name='translateitem',
            options={'verbose_name': 'item'},
        ),
        migrations.AddField(
            model_name='active',
            name='dispose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='active',
            name='leasing',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='active',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='active',
            name='user_function',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
        migrations.AddField(
            model_name='active',
            name='username',
            field=models.CharField(blank=True, max_length=165, null=True),
        ),
        migrations.AlterField(
            model_name='translateitem',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='comentarios'),
        ),
    ]
