# Generated by Django 3.0.2 on 2020-03-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200214_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('translate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.Translate')),
            ],
            options={
                'abstract': False,
            },
            bases=('backend.translate',),
        ),
        migrations.RemoveField(
            model_name='area',
            name='country',
        ),
        migrations.AddField(
            model_name='translate',
            name='document_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Orden de compra'), (2, 'Orden de entrada'), (3, 'Orden de salida'), (4, 'Mantenimiento')], null=True),
        ),
        migrations.AlterField(
            model_name='translate',
            name='destiny_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destiny_area', to='backend.Area', verbose_name='area que recibe'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='destiny_charge',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='cargo de la persona que recibe'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='destiny_person',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='persona que recibe'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='origin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_area', to='backend.Area', verbose_name='area que envia'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='origin_charge',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='cargo de la persona que envia'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='origin_person',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='persona que envia'),
        ),
    ]
