# Generated by Django 3.0.2 on 2020-03-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200320_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.CreateModel(
            name='Maintanance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.CreateModel(
            name='Outcoming',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
