# Generated by Django 3.0.2 on 2020-03-21 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_area_group_groupfield'),
        ('backend', '0011_auto_20200320_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupfield',
            name='group',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backend.translate',),
        ),
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': 'activo', 'verbose_name_plural': 'activo fijo'},
        ),
        migrations.AlterModelOptions(
            name='incoming',
            options={'verbose_name': 'entrada'},
        ),
        migrations.AlterModelOptions(
            name='maintanance',
            options={'verbose_name': 'matenimiento'},
        ),
        migrations.AlterModelOptions(
            name='outcoming',
            options={'verbose_name': 'salida'},
        ),
        migrations.AlterField(
            model_name='active',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Area', verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='active',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Group'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='destiny_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destiny_area', to='utils.Area', verbose_name='area que recibe'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='origin_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_area', to='utils.Area', verbose_name='area que envia'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupField',
        ),
    ]
