# Generated by Django 3.0.2 on 2020-03-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200321_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('ruc', models.CharField(max_length=14, verbose_name='número ruc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
