# Generated by Django 3.0.2 on 2020-03-21 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_area_group_groupfield'),
        ('backend', '0014_auto_20200321_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'inventario', 'verbose_name_plural': 'levantar de inventario'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='estatus',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.Status'),
        ),
    ]
