# Generated by Django 3.0.2 on 2020-03-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'área',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='marca')),
            ],
            options={
                'verbose_name': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'estado',
            },
        ),
        migrations.CreateModel(
            name='GroupField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='nombre en la base de datos')),
                ('label', models.CharField(max_length=65, verbose_name='etiqueta para el usuario')),
                ('input_type', models.CharField(choices=[('TEXT', 'TEXT')], max_length=4)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='utils.Group')),
            ],
            options={
                'verbose_name': 'campo',
            },
        ),
    ]
